### ISSUE TITLE
GraphQl differ

### ISSUE THREAD

**Issue by comtihon** [flussonic/sqlapi#1]
Nice project!
What is the difference with GraphQL? (except syntax)

**Comment by maxlapshin** [comment]
GraphQL is a language and has implementation for javascript.

This library sqlapi is a bridge that allows to expose data inside erlang server via SQL interface.

**Comment by comtihon** [comment]
I was talking about server-side graphql (there are a few even for Erlang).
The use case is the same:
- you have the data on the backend side you would like to expose
- you define schema and implement a data fetcher
- clients can query your service via graphql (with pagination, filtering etc.)

Am I right that this library does the same, but SQL is used instead?

**Comment by maxlapshin** [comment]
exactly.

**Comment by comtihon** [comment]
Thanks!
Good library :)
